[package]
name = "mutex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8"
rand = "0.8.5"
itertools = "0.11.0"
rayon = "1.7.0"